#!/usr/bin/env bash
#
# Commit regenerated data and push it straight to the production branch.
#
#   bash .github/scripts/commit-and-push.sh "<commit message>" [path...]
#
# Used by every workflow that writes generated files to `main`. It exists so
# that the two refresh workflows cannot drift apart: they previously kept
# separate hand-maintained `git add` lists, and the lists disagreed —
# src/lib/generated/warn-summary.json was regenerated by both and committed by
# neither, so the copy in the repo was permanently stale. The set of outputs is
# now declared once, here.
#
# Behaviour:
#   · stages the whole generated surface (-A, so new and deleted files count)
#   · exits 0 without committing when nothing tracked actually changed
#   · rebases onto the remote immediately before every push attempt
#   · retries a bounded number of times, then fails loudly
#   · never force-pushes, never rewrites remote history
#
# Environment:
#   TARGET_BRANCH   branch to push to           (default: main)
#   PUSH_ATTEMPTS   max push attempts           (default: 5)

set -euo pipefail

MESSAGE="${1:-}"
if [ -z "$MESSAGE" ]; then
  echo "::error::commit-and-push.sh requires a commit message as its first argument"
  exit 1
fi
shift || true

BRANCH="${TARGET_BRANCH:-main}"
ATTEMPTS="${PUSH_ATTEMPTS:-5}"

# The canonical set of generated, tracked outputs. Directories rather than file
# lists on purpose: a new generated file is then committed automatically instead
# of silently rotting until someone notices. Callers may override by passing
# paths, but neither refresh workflow does — they share this definition.
DEFAULT_PATHS=(
  "src/lib/generated"
  "public/api"
  "public/data-manifest.json"
  "public/pulse-email.html"
  "public/pulse-email.txt"
)

if [ "$#" -gt 0 ]; then
  PATHS=("$@")
else
  PATHS=("${DEFAULT_PATHS[@]}")
fi

summary() {
  if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
    printf '%s\n' "$*" >>"$GITHUB_STEP_SUMMARY"
  fi
}

# ── Identity ────────────────────────────────────────────────────────────────
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# ── Stage ───────────────────────────────────────────────────────────────────
echo "::group::Staging generated output"
PRESENT=()
for p in "${PATHS[@]}"; do
  if [ -e "$p" ]; then
    PRESENT+=("$p")
    echo "  staging  $p"
  else
    # Not fatal: the two workflows share one path list and legitimately produce
    # overlapping-but-not-identical subsets of it.
    echo "::warning::skipping '$p' — not present in this checkout"
  fi
done

if [ "${#PRESENT[@]}" -eq 0 ]; then
  echo "::error::none of the requested paths exist; nothing could be staged"
  exit 1
fi

git add -A -- "${PRESENT[@]}"
echo "::endgroup::"

# ── Nothing to do? Succeed quietly. ─────────────────────────────────────────
if git diff --cached --quiet; then
  echo "No tracked output changed — nothing to commit, nothing to deploy."
  summary "- **commit:** skipped — no tracked output changed"
  exit 0
fi

echo "::group::Files changed"
git diff --cached --stat
echo "::endgroup::"

CHANGED_COUNT="$(git diff --cached --name-only | wc -l | tr -d ' ')"
summary "- **files changed:** $CHANGED_COUNT"
summary ""
summary '```'
git diff --cached --stat >>"${GITHUB_STEP_SUMMARY:-/dev/null}" || true
summary '```'

# ── Commit ──────────────────────────────────────────────────────────────────
# No [skip ci] marker. Vercel treats [skip ci] as "do not deploy", so the marker
# that was here suppressed the very production deploy this workflow exists to
# trigger. Letting CI run on the data commit is also a feature, not waste: the
# payload-budget and evidence-integrity suites then actually see the new data.
echo "::group::Commit"
git commit -m "$MESSAGE"
COMMIT_SHA="$(git rev-parse --short HEAD)"
echo "committed $COMMIT_SHA"
echo "::endgroup::"
summary "- **commit:** \`$COMMIT_SHA\` — $MESSAGE"

# ── Rebase + push, bounded retry ────────────────────────────────────────────
# Another writer (the other refresh workflow, or a human) can land on main
# between our checkout and our push. Rebasing immediately before each attempt
# keeps the push fast-forward. Force-pushing would "fix" a conflict by
# destroying whatever landed first, so it is never used.
PUSHED=false
for attempt in $(seq 1 "$ATTEMPTS"); do
  echo "::group::Push attempt $attempt of $ATTEMPTS"

  echo "rebasing onto origin/$BRANCH ..."
  if ! git pull --rebase origin "$BRANCH"; then
    # A conflict here means someone changed the same generated files. Resolving
    # it automatically would mean guessing whose data is correct, so the rebase
    # is abandoned and retried from a clean state instead.
    echo "::warning::rebase failed on attempt $attempt — aborting and retrying"
    git rebase --abort || true
    echo "::endgroup::"
    sleep $((attempt * 5))
    continue
  fi
  echo "rebase ok — local branch is now on top of origin/$BRANCH"

  echo "pushing to $BRANCH ..."
  if git push origin "HEAD:refs/heads/$BRANCH"; then
    PUSHED=true
    echo "::endgroup::"
    break
  fi

  echo "::warning::push rejected on attempt $attempt (remote moved, or branch protection)"
  echo "::endgroup::"
  sleep $((attempt * 5))
done

if [ "$PUSHED" != true ]; then
  echo "::error::Could not push to '$BRANCH' after $ATTEMPTS attempts. Nothing was force-pushed and no history was rewritten. If the log shows 'protected branch hook declined', the GitHub Actions bot is not on the bypass list for the ruleset protecting '$BRANCH' — see docs/deployment.md."
  summary "- **push:** FAILED after $ATTEMPTS attempts"
  exit 1
fi

FINAL_SHA="$(git rev-parse --short HEAD)"
echo "Pushed $FINAL_SHA to $BRANCH."
echo "Deployment trigger: Vercel's git integration builds every push to $BRANCH, so production will now rebuild from this commit."
summary "- **push:** \`$FINAL_SHA\` → \`$BRANCH\` (attempt $attempt of $ATTEMPTS)"
summary "- **deploy:** Vercel production build triggered by the push"
