#!/usr/bin/env bash
#
# Commit regenerated data and push it straight to the production branch.
#
#   bash .github/scripts/commit-and-push.sh "<commit message>" [path...]
#
# Used by every workflow that writes generated files to `main`. It exists so
# that the two refresh workflows cannot drift apart: they previously kept
# separate hand-maintained `git add` lists, and the lists disagreed —
# src/lib/generated/warn-summary.json was regenerated by both and committed by
# neither, so the copy in the repo was permanently stale. The set of outputs is
# now declared once, here.
#
# Behaviour:
#   · stages the whole generated surface (-A, so new and deleted files count)
#   · exits 0 without committing when nothing tracked actually changed
#   · rebases onto the remote immediately before every push attempt
#   · retries a bounded number of times, then fails loudly
#   · never force-pushes, never rewrites remote history
#
# Environment:
#   TARGET_BRANCH   branch to push to           (default: main)
#   PUSH_ATTEMPTS   max push attempts           (default: 5)

set -euo pipefail

MESSAGE="${1:-}"
if [ -z "$MESSAGE" ]; then
  echo "::error::commit-and-push.sh requires a commit message as its first argument"
  exit 1
fi
shift || true

BRANCH="${TARGET_BRANCH:-main}"
ATTEMPTS="${PUSH_ATTEMPTS:-5}"

# The canonical set of generated, tracked outputs. Directories rather than file
# lists on purpose: a new generated file is then committed automatically instead
# of silently rotting until someone notices. Callers may override by passing
# paths, but neither refresh workflow does — they share this definition.
DEFAULT_PATHS=(
  "src/lib/generated"
  "public/api"
  "public/newsletter"
  "public/data-manifest.json"
  # The retained source-document store. Written during ingest by the
  # federal-register and executive-actions adapters via putSourceText(), so
  # every run that finds new documents leaves it dirty.
  #
  # Missing from this list between 2026-09-04 and its addition here, and the
  # consequence was not staleness but a hard stop: `git pull --rebase` refuses
  # to run against a dirty tree, so the push below failed five times and the job
  # exited 1. That killed the daily refresh every day from 2026-09-05, and on
  # 2026-09-10 it killed the newsletter BEFORE the send step — the issue was
  # built, validated and cleared for delivery, and no email went out.
  "data/source-text"
)

if [ "$#" -gt 0 ]; then
  PATHS=("$@")
else
  PATHS=("${DEFAULT_PATHS[@]}")
fi

summary() {
  if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
    printf '%s\n' "$*" >>"$GITHUB_STEP_SUMMARY"
  fi
}

# ── Identity ────────────────────────────────────────────────────────────────
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# ── Stage ───────────────────────────────────────────────────────────────────
echo "::group::Staging generated output"
PRESENT=()
for p in "${PATHS[@]}"; do
  if [ -e "$p" ]; then
    PRESENT+=("$p")
    echo "  staging  $p"
  else
    # Not fatal: the two workflows share one path list and legitimately produce
    # overlapping-but-not-identical subsets of it.
    echo "::warning::skipping '$p' — not present in this checkout"
  fi
done

if [ "${#PRESENT[@]}" -eq 0 ]; then
  echo "::error::none of the requested paths exist; nothing could be staged"
  exit 1
fi

git add -A -- "${PRESENT[@]}"
echo "::endgroup::"

# ── Anything regenerated but NOT in the path list? ──────────────────────────
# This is the check that was missing. When a new generated output appears
# outside the list above, the working tree stays dirty after staging, and the
# only symptom used to be `git pull --rebase` refusing to run — reported as
# "cannot pull with rebase: You have unstaged changes" and then, five attempts
# later, as an error suggesting branch protection. The real cause was never
# named, so the daily refresh failed for six days and the newsletter for a week
# before anyone traced it.
#
# Named here instead, with the files, so the next omission is one line in the
# log rather than an archaeology exercise. A warning and not an error: the
# autostash below means the push still succeeds, and stopping the newsletter
# because a cache file is uncommitted would be the same trade that caused this
# incident.
STRAY="$(git diff --name-only)"
if [ -n "$STRAY" ]; then
  echo "::group::Regenerated but not staged"
  echo "$STRAY" | sed 's/^/  /'
  echo "::endgroup::"
  echo "::warning::$(echo "$STRAY" | wc -l | tr -d ' ') tracked file(s) were regenerated but are not in this script's path list, so they will NOT be committed. If they are generated output, add their path to DEFAULT_PATHS in .github/scripts/commit-and-push.sh."
fi

# ── Nothing to do? Succeed quietly. ─────────────────────────────────────────
if git diff --cached --quiet; then
  echo "No tracked output changed — nothing to commit, nothing to deploy."
  summary "- **commit:** skipped — no tracked output changed"
  exit 0
fi

echo "::group::Files changed"
git diff --cached --stat
echo "::endgroup::"

CHANGED_COUNT="$(git diff --cached --name-only | wc -l | tr -d ' ')"
summary "- **files changed:** $CHANGED_COUNT"
summary ""
summary '```'
git diff --cached --stat >>"${GITHUB_STEP_SUMMARY:-/dev/null}" || true
summary '```'

# ── Commit ──────────────────────────────────────────────────────────────────
# No [skip ci] marker. Vercel treats [skip ci] as "do not deploy", so the marker
# that was here suppressed the very production deploy this workflow exists to
# trigger. Letting CI run on the data commit is also a feature, not waste: the
# payload-budget and evidence-integrity suites then actually see the new data.
echo "::group::Commit"
git commit -m "$MESSAGE"
COMMIT_SHA="$(git rev-parse --short HEAD)"
echo "committed $COMMIT_SHA"
echo "::endgroup::"
summary "- **commit:** \`$COMMIT_SHA\` — $MESSAGE"

# ── Rebase + push, bounded retry ────────────────────────────────────────────
# Another writer (the other refresh workflow, or a human) can land on main
# between our checkout and our push. Rebasing immediately before each attempt
# keeps the push fast-forward. Force-pushing would "fix" a conflict by
# destroying whatever landed first, so it is never used.
PUSHED=false
for attempt in $(seq 1 "$ATTEMPTS"); do
  echo "::group::Push attempt $attempt of $ATTEMPTS"

  echo "rebasing onto origin/$BRANCH ..."
  # --autostash, because a dirty working tree must never be able to stop a
  # publish. Callers legitimately commit a subset (social.yml passes two files),
  # and any regenerated output outside the path list leaves the tree dirty —
  # which made `git pull --rebase` refuse outright and took down the daily
  # refresh and one week's newsletter. Git stashes the remainder, rebases, and
  # reapplies it; nothing is discarded, and the warning above still says what
  # was left behind.
  if ! git -c rebase.autoStash=true pull --rebase origin "$BRANCH"; then
    # A conflict here means someone changed the same generated files. Resolving
    # it automatically would mean guessing whose data is correct, so the rebase
    # is abandoned and retried from a clean state instead.
    echo "::warning::rebase failed on attempt $attempt — aborting and retrying"
    git rebase --abort || true
    echo "::endgroup::"
    sleep $((attempt * 5))
    continue
  fi
  echo "rebase ok — local branch is now on top of origin/$BRANCH"

  echo "pushing to $BRANCH ..."
  if git push origin "HEAD:refs/heads/$BRANCH"; then
    PUSHED=true
    echo "::endgroup::"
    break
  fi

  echo "::warning::push rejected on attempt $attempt (remote moved, or branch protection)"
  echo "::endgroup::"
  sleep $((attempt * 5))
done

if [ "$PUSHED" != true ]; then
  echo "::error::Could not push to '$BRANCH' after $ATTEMPTS attempts. Nothing was force-pushed and no history was rewritten. If the log shows 'protected branch hook declined', the GitHub Actions bot is not on the bypass list for the ruleset protecting '$BRANCH' — see docs/deployment.md."
  summary "- **push:** FAILED after $ATTEMPTS attempts"
  exit 1
fi

FINAL_SHA="$(git rev-parse --short HEAD)"
echo "Pushed $FINAL_SHA to $BRANCH."
echo "Deployment trigger: Vercel's git integration builds every push to $BRANCH, so production will now rebuild from this commit."
summary "- **push:** \`$FINAL_SHA\` → \`$BRANCH\` (attempt $attempt of $ATTEMPTS)"
summary "- **deploy:** Vercel production build triggered by the push"
