// =============================================================================
// EVENT SEARCH INDEX
//
// The index is what /what-changed ships to the browser so a reader can search
// the whole archive without downloading it. Two classes of risk:
//
//   1. The index DRIFTS from the store, and search returns things the store no
//      longer holds — or misses things it does. Both are generated by the same
//      run, and these tests hold that contract.
//
//   2. A filter quietly widens instead of narrowing, so a reader who filtered to
//      "major" sees routine notices and concludes something changed when it did
//      not.
// =============================================================================
import { describe, it, expect } from "vitest";
import {
  EVENT_INDEX,
  filterEvents,
  hasActiveFilters,
  facetCounts,
  groupByDay,
  indexedSourceKeys,
  type IndexedEvent,
} from "@/lib/event-index";
import { EVENTS } from "@/lib/event-store";
import { SOURCE_BY_KEY } from "@/lib/sources";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ev = (over: Partial<IndexedEvent> = {}): IndexedEvent => ({
  id: "federal_register:1",
  title: "H-1B specialty occupation rule",
  publishedAt: "2026-07-01",
  effectiveAt: null,
  scheduled: false,
  severity: "major",
  classification: "final_rule",
  sourceKey: "federal_register",
  sourceUrl: "https://www.federalregister.gov/x",
  summary: "A rule about specialty occupations.",
  entityIds: ["agency:uscis", "visa:h-1b"],
  ...over,
});

// =============================================================================
// The index must describe the store it was built from.
// =============================================================================
describe("index integrity", () => {
  it("covers exactly the events the store publishes", () => {
    // Generated by the same run as the store. If these ever diverge, search is
    // answering from a different archive than the page renders.
    expect(EVENT_INDEX.length).toBe(EVENTS.length);
    expect(new Set(EVENT_INDEX.map((e) => e.id))).toEqual(new Set(EVENTS.map((e) => e.id)));
  });

  it("carries the same severity and date for every event", () => {
    const byId = new Map(EVENTS.map((e) => [e.id, e]));
    for (const i of EVENT_INDEX) {
      const full = byId.get(i.id)!;
      expect(i.severity, `${i.id} severity drifted`).toBe(full.severity);
      expect(i.publishedAt, `${i.id} date drifted`).toBe(full.publishedAt);
      expect(i.classification, `${i.id} classification drifted`).toBe(full.classification);
      expect(i.sourceUrl, `${i.id} source URL drifted`).toBe(full.sourceUrl);
    }
  });

  it("never truncates a summary without marking it", () => {
    for (const i of EVENT_INDEX) {
      if (i.summary.length > 221) {
        expect(i.summary.endsWith("…"), `${i.id} is over-length but unmarked`).toBe(true);
      }
    }
  });

  it("points every indexed event at a registered source", () => {
    for (const key of indexedSourceKeys()) {
      expect(SOURCE_BY_KEY[key], `unknown source ${key}`).toBeDefined();
    }
  });

  it("is sorted newest first", () => {
    for (let i = 1; i < EVENT_INDEX.length; i++) {
      expect(EVENT_INDEX[i - 1].publishedAt >= EVENT_INDEX[i].publishedAt).toBe(true);
    }
  });

  it("ships no draft events to the browser", () => {
    // publishableEvents() filters drafts out of EVENTS; the index is built from
    // the merged store, so this guards the path a reader actually receives.
    const draftIds = new Set(EVENTS.filter((e) => e.reviewStatus === "draft").map((e) => e.id));
    expect(EVENT_INDEX.filter((i) => draftIds.has(i.id))).toEqual([]);
  });
});

// =============================================================================
// Filters must NARROW. A filter that widens misinforms.
// =============================================================================
describe("filtering", () => {
  const sample = [
    ev({ id: "a", severity: "major", sourceKey: "federal_register", title: "H-1B cap rule" }),
    ev({ id: "b", severity: "routine", sourceKey: "cbp_encounters", title: "CBP encounters data" }),
    ev({ id: "c", severity: "notable", sourceKey: "uscis_newsroom", title: "Asylum processing update" }),
  ];

  it("returns everything when nothing is set", () => {
    expect(filterEvents(sample, {})).toHaveLength(3);
  });

  it("filters by severity", () => {
    expect(filterEvents(sample, { severity: ["major"] }).map((e) => e.id)).toEqual(["a"]);
    expect(filterEvents(sample, { severity: ["major", "notable"] }).map((e) => e.id)).toEqual(["a", "c"]);
  });

  it("filters by source", () => {
    expect(filterEvents(sample, { sourceKey: ["cbp_encounters"] }).map((e) => e.id)).toEqual(["b"]);
  });

  it("combines filters as AND, never OR", () => {
    // Two filters must narrow. If they widened, a reader filtering to "major
    // Federal Register" would be shown routine CBP releases.
    expect(filterEvents(sample, { severity: ["major"], sourceKey: ["cbp_encounters"] })).toEqual([]);
    expect(
      filterEvents(sample, { severity: ["major"], sourceKey: ["federal_register"] }).map((e) => e.id)
    ).toEqual(["a"]);
  });

  it("requires every search term, so adding a word narrows", () => {
    const events = [
      ev({ id: "x", title: "H-1B cap reached", summary: "" }),
      ev({ id: "y", title: "H-1B registration opens", summary: "" }),
    ];
    expect(filterEvents(events, { q: "h-1b" })).toHaveLength(2);
    expect(filterEvents(events, { q: "h-1b registration" }).map((e) => e.id)).toEqual(["y"]);
  });

  it("searches the summary as well as the title", () => {
    const events = [ev({ id: "x", title: "A rule", summary: "This concerns asylum seekers." })];
    expect(filterEvents(events, { q: "asylum" })).toHaveLength(1);
  });

  it("is case-insensitive", () => {
    expect(filterEvents(sample, { q: "H-1B" })).toHaveLength(1);
    expect(filterEvents(sample, { q: "h-1b" })).toHaveLength(1);
  });

  it("filters by linked entity, for the 'does this affect me' question", () => {
    const events = [
      ev({ id: "x", entityIds: ["visa:h-1b"] }),
      ev({ id: "y", entityIds: ["visa:f-1"] }),
    ];
    expect(filterEvents(events, { entityId: "visa:h-1b" }).map((e) => e.id)).toEqual(["x"]);
  });

  it("filters by inclusive date bounds", () => {
    const events = [
      ev({ id: "old", publishedAt: "2025-01-01" }),
      ev({ id: "mid", publishedAt: "2026-01-01" }),
      ev({ id: "new", publishedAt: "2026-07-01" }),
    ];
    expect(filterEvents(events, { from: "2026-01-01" }).map((e) => e.id)).toEqual(["mid", "new"]);
    expect(filterEvents(events, { to: "2026-01-01" }).map((e) => e.id)).toEqual(["old", "mid"]);
  });

  it("treats whitespace as no query rather than matching nothing", () => {
    expect(filterEvents(sample, { q: "   " })).toHaveLength(3);
  });
});

describe("active-filter detection", () => {
  it("is false for an empty or whitespace-only state", () => {
    expect(hasActiveFilters({})).toBe(false);
    expect(hasActiveFilters({ q: "   " })).toBe(false);
    expect(hasActiveFilters({ severity: [], sourceKey: [] })).toBe(false);
  });

  it("is true as soon as anything is set", () => {
    expect(hasActiveFilters({ q: "visa" })).toBe(true);
    expect(hasActiveFilters({ severity: ["major"] })).toBe(true);
    expect(hasActiveFilters({ entityId: "visa:h-1b" })).toBe(true);
  });
});

describe("facets", () => {
  it("counts the result set it is given", () => {
    const f = facetCounts([ev({ severity: "major" }), ev({ severity: "major" }), ev({ severity: "routine" })]);
    expect(f.bySeverity).toEqual({ major: 2, routine: 1 });
  });

  it("returns empty counts for an empty set rather than throwing", () => {
    expect(facetCounts([])).toEqual({ bySeverity: {}, byClassification: {}, bySource: {} });
  });
});

describe("day grouping", () => {
  it("groups by publication day, newest first", () => {
    const grouped = groupByDay([
      ev({ id: "a", publishedAt: "2026-07-01" }),
      ev({ id: "b", publishedAt: "2026-07-05" }),
      ev({ id: "c", publishedAt: "2026-07-01" }),
    ]);
    expect(grouped.map((g) => g.date)).toEqual(["2026-07-05", "2026-07-01"]);
    expect(grouped[1].events.map((e) => e.id)).toEqual(["a", "c"]);
  });

  it("returns nothing for an empty set", () => {
    expect(groupByDay([])).toEqual([]);
  });
});

// =============================================================================
// PERFORMANCE BUDGET
//
// The index is downloaded by every visitor to /what-changed. It grows with the
// archive, and nothing about adding an adapter makes that growth visible — so
// the budget is asserted here, where crossing it fails the build instead of
// quietly costing every reader on a slow connection.
// =============================================================================
describe("index size budget", () => {
  const root = fileURLToPath(new URL("..", import.meta.url));
  const raw = readFileSync(join(root, "src/lib/generated/events-index.json"), "utf8");
  const kb = raw.length / 1024;

  it("stays inside the browser payload budget", () => {
    // 400KB uncompressed is roughly 80KB over the wire. Past that the archive
    // needs a bounded window shipped to the client with the older tail served
    // separately — a real architectural change, and this test is the trigger
    // for having that conversation rather than discovering it in production.
    expect(kb, `events-index.json is ${kb.toFixed(0)}KB`).toBeLessThan(400);
  });

  it("carries no field a result row does not use", () => {
    // Every field is paid for by every visitor. Impact records, limitations and
    // evidence quotes belong in the store, not the browser.
    const allowed = new Set([
      "id", "title", "publishedAt", "effectiveAt", "scheduled", "severity",
      "classification", "sourceKey", "sourceUrl", "summary", "entityIds",
    ]);
    for (const e of EVENT_INDEX.slice(0, 40)) {
      for (const key of Object.keys(e)) {
        expect(allowed.has(key), `index carries unused field "${key}"`).toBe(true);
      }
    }
  });

  it("ships no evidence quotes or limitations to the browser", () => {
    for (const e of EVENT_INDEX as unknown as Record<string, unknown>[]) {
      expect(e.impact).toBeUndefined();
      expect(e.limitations).toBeUndefined();
      expect(e.entities).toBeUndefined();
    }
  });
});
