// =============================================================================
// DEPARTMENT OF LABOR — OFLC ANNOUNCEMENTS ADAPTER
//
// The Office of Foreign Labor Certification runs the front half of employment
// immigration: PERM, the H-2A and H-2B programs, prevailing wage determinations,
// and the FLAG filing system. An employer's case starts here, months before
// USCIS sees a petition, so an OFLC processing change reaches people well before
// anything appears in the Federal Register.
//
// -----------------------------------------------------------------------------
// WHY OFLC AND NOT THE MAIN DOL NEWS FEED
// -----------------------------------------------------------------------------
// dol.gov publishes a proper RSS feed, and it was measured: of the ten most
// recent releases, ZERO were immigration-related. It is dominated by OSHA
// citations, wage-and-hour recoveries, and unemployment claims. Ingesting it
// would mean running a filter that rejects almost everything, to catch an
// occasional item that OFLC announces directly anyway.
//
// DOL RULEMAKING IS ALREADY COVERED. The Federal Register adapter tracks both
// `labor-department` and `employment-and-training-administration`, so H-2A and
// H-2B rules reach the store through it. What OFLC adds is the operational
// layer that never becomes a rule: filing windows, system outages, processing
// resumptions, program guidance.
//
// -----------------------------------------------------------------------------
// THE DATE COMES FROM THE URL, NOT THE PROSE
// -----------------------------------------------------------------------------
// Each announcement links to /announcement/YYYY-MM-DD. That path is an
// unambiguous ISO date generated by the CMS, whereas the visible "June 30, 2026"
// is display text that could be reformatted at any time. The path is primary and
// the visible date is a cross-check: if they disagree, the announcement is
// skipped rather than dated by a coin flip.
//
// -----------------------------------------------------------------------------
// RELEASE NOTES ARE NOT POLICY
// -----------------------------------------------------------------------------
// Most of what OFLC posts is software release notes for the FLAG and PERM filing
// systems — "PW filers can now respond to multiple RFIs on a single case". Real,
// worth recording, and not a policy change. They are `routine`, so they stay in
// the archive without crowding a feed whose promise is what changed.
// =============================================================================

import { capEvents } from "../adapters";
import type { AdapterContext, AdapterResult, SourceAdapter } from "../adapters";
import type {
  EventClassification,
  EventEntityLink,
  EventSeverity,
  ImmigrationEvent,
} from "../events";
import { entityId } from "../entities";
import { resolveEntityMentions } from "../resolve";
import { extractImpact } from "../extract-impact";
import { plainText, richText, containsAnyTerm } from "../text";

const ANNOUNCEMENTS_URL = "https://flag.dol.gov/announcements";
const UA = "ImmigrationClock/1.0 (+https://immigrationclock.com)";
const SOURCE_KEY = "dol_oflc";

export interface OflcAnnouncement {
  /** ISO date taken from the announcement's own URL path. */
  publishedAt: string | null;
  title: string;
  body: string | null;
  url: string;
  /** The human-readable date as displayed, kept for cross-checking. */
  displayDate: string | null;
}

// -----------------------------------------------------------------------------
// Parsing
// -----------------------------------------------------------------------------

export function splitRows(html: string): string[] {
  return html.split(/<div class="announcement-wrapper views-row">/).slice(1);
}

const MONTHS: Record<string, string> = {
  january: "01", february: "02", march: "03", april: "04", may: "05", june: "06",
  july: "07", august: "08", september: "09", october: "10", november: "11", december: "12",
};

/** "June 30, 2026" → "2026-06-30". Null when it is not that shape. */
export function parseDisplayDate(raw: string | null): string | null {
  if (!raw) return null;
  const m = /^([A-Za-z]+)\s+(\d{1,2}),\s*(\d{4})$/.exec(plainText(raw));
  if (!m) return null;
  const mm = MONTHS[m[1].toLowerCase()];
  if (!mm) return null;
  return `${m[3]}-${mm}-${m[2].padStart(2, "0")}`;
}

/** The ISO date embedded in /announcement/YYYY-MM-DD. */
export function parsePathDate(href: string): string | null {
  const m = /\/announcement\/(\d{4}-\d{2}-\d{2})/.exec(href);
  return m ? m[1] : null;
}

export function parseRow(row: string): OflcAnnouncement | null {
  const linkMatch = /announcement-list-title">\s*<a href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/.exec(row);
  if (!linkMatch) return null;

  const href = linkMatch[1];
  const title = plainText(linkMatch[2]);
  if (!title) return null;

  const displayDate = plainText(/announcement-list-date'>([^<]*)</.exec(row)?.[1] ?? "") || null;
  const pathDate = parsePathDate(href);
  const shownDate = parseDisplayDate(displayDate);

  // Primary is the URL path. If the visible date disagrees, we have two
  // conflicting claims about when this happened and no basis to prefer one, so
  // the announcement is dropped rather than dated by a coin flip.
  let publishedAt: string | null = pathDate;
  if (pathDate && shownDate && pathDate !== shownDate) publishedAt = null;
  if (!publishedAt && !pathDate) publishedAt = shownDate;

  const rawBody = /announcement-list-body">([\s\S]*?)<\/div>/.exec(row)?.[1] ?? null;

  return {
    publishedAt,
    title,
    body: rawBody ? richText(rawBody) || null : null,
    url: href.startsWith("http") ? href : `https://flag.dol.gov${href}`,
    displayDate,
  };
}

export function parseAnnouncementsPage(html: string): OflcAnnouncement[] {
  const out: OflcAnnouncement[] = [];
  for (const row of splitRows(html)) {
    const a = parseRow(row);
    if (a) out.push(a);
  }
  return out;
}

// -----------------------------------------------------------------------------
// Classification and severity
// -----------------------------------------------------------------------------

/** Software release notes for the FLAG / PERM filing systems. */
const SYSTEM_NOTE_TERMS = [
  "release notes", "online filing release", "technical release notes",
  "system maintenance", "scheduled maintenance", "system outage", "site maintenance",
];

/** Outreach rather than policy. */
const OUTREACH_TERMS = ["webinar", "listening session", "stakeholder call", "technical assistance", "town hall"];

/** Things that change what a filer can or must do. */
const POLICY_TERMS = [
  "guidance", "policy", "final rule", "interim final rule", "regulation",
  "prevailing wage", "filing window", "deadline", "suspend", "suspension",
  "resume", "resumed", "moratorium", "processing times", "record retention",
  "eligibility", "requirement", "attestation", "audit",
];

export function isSystemNote(a: OflcAnnouncement): boolean {
  return containsAnyTerm(a.title, SYSTEM_NOTE_TERMS);
}

export function classify(a: OflcAnnouncement): EventClassification {
  const hay = `${a.title} ${a.body ?? ""}`;
  if (containsAnyTerm(hay, ["final rule", "interim final rule"])) return "final_rule";
  if (containsAnyTerm(hay, ["proposed rule"])) return "proposed_rule";
  if (containsAnyTerm(a.title, ["deadline", "filing window", "filing period", "cap"])) return "deadline";
  if (isSystemNote(a)) return "updated_information";
  return "announcement";
}

/**
 * Severity by explicit rule.
 *
 * `major` is deliberately hard to reach here: OFLC rarely changes eligibility by
 * announcement, and when it does the change is normally a rule that the Federal
 * Register adapter already reports as major. Double-counting it would inflate
 * the feed with two majors for one change.
 */
export function severity(a: OflcAnnouncement, classification: EventClassification): EventSeverity {
  if (classification === "final_rule" || classification === "deadline") return "major";
  // Release notes and outreach are real, and neither changes any obligation.
  if (isSystemNote(a) || containsAnyTerm(a.title, OUTREACH_TERMS)) return "routine";
  if (containsAnyTerm(`${a.title} ${a.body ?? ""}`, POLICY_TERMS)) return "notable";
  return "routine";
}

export function stableId(a: OflcAnnouncement): string {
  const slug = a.url
    .replace(/^https?:\/\/[^/]+/, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
  return `${SOURCE_KEY}:${slug.slice(0, 100)}`;
}

// -----------------------------------------------------------------------------
// Event construction
// -----------------------------------------------------------------------------

export function toEvent(a: OflcAnnouncement, verifiedAt: string): ImmigrationEvent {
  const classification = classify(a);
  const links: EventEntityLink[] = [
    { entityId: entityId("agency", "dol"), relation: "issued_by", basis: "explicit", confidence: 1 },
    { entityId: entityId("topic", "employers"), relation: "categorized_as", basis: "explicit", confidence: 1 },
  ];

  for (const m of resolveEntityMentions(`${a.title} ${a.body ?? ""}`)) {
    if (links.some((l) => l.entityId === m.entityId)) continue;
    links.push({ entityId: m.entityId, relation: "mentions", basis: "matched", confidence: m.confidence });
  }

  const systemNote = isSystemNote(a);

  return {
    id: stableId(a),
    sourceKey: SOURCE_KEY,
    issuingAgencyId: entityId("agency", "dol"),
    classification,
    severity: severity(a, classification),
    title: a.title,
    summary: a.body?.trim() || "OFLC published no summary text with this announcement.",
    publishedAt: a.publishedAt!,
    // OFLC announcements state an effective date in the body when there is one;
    // the listing does not publish one as a field, so we do not assert one.
    effectiveAt: null,
    lastVerifiedAt: verifiedAt,
    sourceUrl: a.url,
    entities: links,
    impact: extractImpact({
      title: a.title,
      abstract: a.body ?? undefined,
      agencyIds: [entityId("agency", "dol")],
      effectiveAt: null,
    }),
    reviewStatus: "auto",
    limitations: [
      systemNote
        ? "This is a release note for OFLC's online filing systems. It describes how the filing software behaves, not what the law requires."
        : "OFLC administers the labor-certification step that comes BEFORE a USCIS petition. An OFLC certification is not a visa, not an approval, and not permission to work — it is one prerequisite among several.",
      "The announcements listing does not publish an effective date as a field. Where an announcement states one, it is in the text of the announcement itself.",
      ...(a.body ? [] : ["OFLC published no summary text for this announcement; read the original."]),
    ],
  };
}

// -----------------------------------------------------------------------------
// Fetch
// -----------------------------------------------------------------------------

async function fetchEvents(ctx: AdapterContext): Promise<AdapterResult> {
  const key = "dol-oflc";
  if (ctx.offline) {
    return { adapterKey: key, events: [], warnings: ["offline: skipped"], failed: false };
  }

  let html: string;
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 30_000);
    const res = await fetch(ANNOUNCEMENTS_URL, {
      headers: { "User-Agent": UA },
      signal: controller.signal,
    }).finally(() => clearTimeout(timer));
    if (!res.ok) {
      return { adapterKey: key, events: [], warnings: [`HTTP ${res.status} from ${ANNOUNCEMENTS_URL}`], failed: true };
    }
    html = await res.text();
  } catch (err) {
    return {
      adapterKey: key,
      events: [],
      warnings: [`fetch failed: ${(err as Error)?.message ?? String(err)}`],
      failed: true,
    };
  }

  const rows = splitRows(html);
  if (rows.length === 0) {
    // Same contract as the USCIS Policy Manual scraper: an empty success would
    // render as a quiet quarter at OFLC, which is a lie of omission.
    return {
      adapterKey: key,
      events: [],
      warnings: [
        "no announcement rows found — the OFLC page structure has changed. Reporting failure rather than an empty success.",
      ],
      failed: true,
    };
  }

  const warnings: string[] = [];
  const parsed: OflcAnnouncement[] = [];
  let unparseable = 0;
  let undated = 0;

  for (const row of rows) {
    const a = parseRow(row);
    if (!a) {
      unparseable++;
      continue;
    }
    if (!a.publishedAt) {
      undated++;
      continue;
    }
    parsed.push(a);
  }

  if (unparseable > 0) warnings.push(`${unparseable} row(s) did not match the expected structure`);
  if (undated > 0) {
    warnings.push(
      `${undated} announcement(s) had no usable date, or a URL date conflicting with the displayed date, and were skipped`
    );
  }

  if (parsed.length === 0 || parsed.length < rows.length * 0.5) {
    return {
      adapterKey: key,
      events: [],
      warnings: [
        ...warnings,
        `only ${parsed.length} of ${rows.length} row(s) parsed — treating as structural drift rather than publishing a partial view`,
      ],
      failed: true,
    };
  }

  const verifiedAt = new Date().toISOString().slice(0, 10);
  const inWindow = parsed.filter((a) => a.publishedAt! >= ctx.since);
  const capped = capEvents(inWindow, ctx.limit);

  return {
    adapterKey: key,
    events: capped.events.map((a) => toEvent(a, verifiedAt)),
    warnings: [...warnings, ...capped.warnings],
    failed: false,
  };
}

export const dolOflcAdapter: SourceAdapter = {
  key: "dol-oflc",
  name: "DOL Office of Foreign Labor Certification",
  sourceKey: SOURCE_KEY,
  status: "ready",
  coverage:
    "OFLC announcements covering PERM, H-2A, H-2B, prevailing wage, and the FLAG filing system — the labor-certification step that comes before a USCIS petition. Filing-system release notes and webinars are recorded as routine, because they are real but change no obligation. DOL rulemaking is not duplicated here: the Federal Register adapter already tracks the labor-department and employment-and-training-administration slugs.",
  fetchEvents,
};

export const __testing = {
  splitRows,
  parseRow,
  parsePathDate,
  parseDisplayDate,
  parseAnnouncementsPage,
  isSystemNote,
  classify,
  severity,
  stableId,
  toEvent,
};
